V1
firstandthird/s3put pull request #1
Opened 2016-09-19 21:18 UTC by orthagonal

2016-09-19 21:20 UTC, jgallen23 commented on main.js
> +    fs.mkdirSync('build');
what is this for?

2016-09-19 21:21 UTC, jgallen23 commented on lib/commonAWS.js
> +'use strict';
think we could pull this out into a separate module?

2016-09-19 21:22 UTC, jgallen23 commented on cli.js
> +    default: 's3-bucket'
no default.  should be required to set

2016-09-19 21:22 UTC, jgallen23 commented on lib/image.js
> +  imagemin([file], 'build/', options).then(handleResult);
what about building to a temp directory?

2016-09-19 21:23 UTC, jgallen23 requested changes
overall, looks good

2016-09-19 23:12 UTC, orthagonal commented on lib/commonAWS.js
> +'use strict';
Definitely, we are just going to keep reusing this code for our AWS stuff.  Make a repo for it and add a readme with any specs you want and I'll switch over to it.

2016-09-19 23:24 UTC, orthagonal commented on lib/image.js
> +  imagemin([file], 'build/', options).then(handleResult);
That's what the 'mkdir' is doing there, making sure the 'build' directory is present where the files are going to be stored.

2016-09-19 23:31 UTC, orthagonal commented on main.js
> +    fs.mkdirSync('build');
Imagemin wants to read/write things from file, so I had it make a temp working directory.

2016-09-20 05:18 UTC, jgallen23 commented on lib/image.js
> +  imagemin([file], 'build/', options).then(handleResult);
that's not really a temp directory. look at os.tmpdir

2016-09-20 05:18 UTC, jgallen23 requested changes

2016-09-20 05:18 UTC, jgallen23 commented on cli.js
> +    default: 's3-bucket'
ping

2016-09-20 15:04 UTC, orthagonal commented on cli.js
> +    default: 's3-bucket'
Committed the code for this yesterday, but was waiting on other feedback before pushing the commit (which causes Github to hide our comments pertaining to the old commit)

2016-09-20 15:06 UTC, orthagonal commented on lib/image.js
> +  imagemin([file], 'build/', options).then(handleResult);
Oh I didn't know about that one, that's very nice.

2016-09-28 03:53 UTC, jgallen23 commented
Error: Cannot find module 'imagemin-mozjpeg'

2016-09-28 03:53 UTC, jgallen23 commented
```
20:51 $ node ~/libraries/s3put/cli.js --profile ft --bucket project-hub hero.jpg                                                                        
Unable to locate profile ft in file /home/ubuntu/.aws/config.
Falling back to us-east-1
{ ETag: '"d41d8cd98f00b204e9800998ecf8427e"',
  Location: 'https://project-hub.s3.amazonaws.com/hero.jpg',
  key: 'hero.jpg',
  Key: 'hero.jpg',
  Bucket: 'project-hub' }
```

uploaded a file with 0 bytes

2016-09-28 19:54 UTC, merged