uses aws-creds
firstandthird/s3put pull request #9
Opened 2016-11-23 19:19 UTC by orthagonal

2016-11-23 19:40 UTC, jgallen23 requested changes

2016-11-23 19:40 UTC, jgallen23 commented on package.json
> -  "bin": {
why was this removed?

2016-11-23 19:40 UTC, jgallen23 commented on test/lib.test.js
> -      profile: process.env.AWS_PROFILE
why was this removed?

2016-11-25 16:44 UTC, orthagonal commented on test/lib.test.js
> -      profile: process.env.AWS_PROFILE
There was a duplicate test here that had gotten committed previously and which I removed here.  We're not actually losing/changing any functionality with this change, Git's review is just making it look that way.

2016-11-29 22:50 UTC, merged